# Generated by Django 3.0.8 on 2020-07-17 23:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('solution', models.FileField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])])),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FileField(blank=True, default='media/output.txt', null=True, upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coder.Question')),
            ],
        ),
    ]
