# Generated by Django 3.0.8 on 2020-07-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0004_auto_20200718_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='result',
            field=models.CharField(blank=True, default='answer', max_length=100, null=True),
        ),
    ]
