# Generated by Django 3.0.8 on 2020-07-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0005_auto_20200718_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
