# Generated by Django 3.0.8 on 2020-07-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0006_auto_20200718_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
