# Generated by Django 3.0.8 on 2020-07-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0009_question_iscorrect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='iscorrect',
        ),
        migrations.AddField(
            model_name='answer',
            name='iscorrect',
            field=models.BooleanField(default=False),
        ),
    ]
