# Generated by Django 3.0.8 on 2020-07-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0010_auto_20200721_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='iscorrect',
            field=models.BooleanField(default=False),
        ),
    ]
